#!/bin/sh

. ../../../scripts/test-utils.sh

fpl_write_eps=../../../bin/fpl-write-eps

run_test()
{
  infile=$1
  if test -n "$2"
  then
    outfile=$2
  else
    outfile=$infile
  fi
  $fpl_write_eps < $infile.txt > $outfile.out.eps 2>&1
}

. ./tests.sh

# Default tests
for t in $tests
do
  echo "
$t()
{
  run_test $t
}"
done > default-tests.sh
. ./default-tests.sh

run_suite $tests
