#!/bin/sh -e

. ../../../scripts/test-utils.sh

fpl_extract_xml="../src/fpl_extract_xml/__main__.py"

compare()
{
  outfile=$1
  diff -u $outfile.ref.txt $outfile.out.txt > $outfile.diff.txt 2>&1
}

run_test()
{
  args=$1
  infile=$2
  if test -n "$3"
  then
    outfile=$3
  else
    outfile=$infile
  fi
  $fpl_extract_xml $args $infile.xml > $outfile.out.txt 2>&1
  compare $outfile
}

. ./tests.sh

# Default tests
for t in $tests
do
  echo "
$t()
{
  rm -f $t/*.out.xml
  run_test '-d '$t $t
  for file in \`ls $t/*.ref.xml\`
  do
    base=\`basename \$file .ref.xml\`
    mv $t/\$base.xml $t/\$base.out.xml
    diff -u --ignore-space-change $t/\$base.out.xml \$file
  done
}"
done > default-tests.sh
. ./default-tests.sh

run_suite $tests
