#!/bin/sh -e

# Go to the working directory, so that relative paths work as expected
wd=`dirname $0`
cd $wd

if test $# -gt 1
then
  echo 'usage: install dest-dir' 1>&2
  echo '       install' 1>&2
  exit 1
fi

if test -n "$1" 
then
  dest=$1
else
  dest=bin
fi

dir=`dirname $dest`
dir=`cd $dir; pwd`
base=`basename $dest`
dest=$dir/$base

scala_tools="
fpl-convert-xml
fpl-layout
fpl-write-pic
"

echo "Building jar files"
sbt assembly

mkdir -p $dest

echo "Installing tools at $dest"

# Install Scala tools
for tool in $scala_tools
do
  jar=`find tools/$tool -name "*$name*assembly*.jar"`
  cp $jar $dest/$tool.jar
  echo '#!/bin/sh

  java -jar `dirname $0`/'$tool'.jar "$@"' > $dest/$tool
  chmod +x $dest/$tool
done

# Install fpl-extract-xml
src=tools/fpl-extract-xml/src
cp $src/fpl-extract-xml $dest
chmod +x $dest/fpl-extract-xml

# Install fpl-write-eps
src=tools/fpl-write-eps/src
sed 's;$FPL_BIN;`dirname $0`;g' < $src/fpl-write-eps > $dest/fpl-write-eps
chmod +x $dest/fpl-write-eps
