#!/bin/sh

# ----------------------------------------------------------------------
# fpl-extract-xml
# Extract connection groups from F Prime topology XML
# ----------------------------------------------------------------------

usage() {
  echo 'usage: fpl-extract-xml -v' >&2
  echo '       fpl-extract-xml [-d output-dir] [files]' >&2
  exit 1
}

dir=""

while :; do
  case $1 in
    -v|--version)
      echo 'fpl-extract-xml version 1.0'
      exit 0 ;;
    -d)
      dir=$2
      shift ;;
    --)
      shift
      break ;;
    -?*)
      usage ;;
    *)
      break ;;
  esac
  shift
done

if test -n "$dir"
then
  diropt="-v dir=$dir"
fi

awk -f $FPL_BIN/fpl-extract-xml.awk $diropt $@
