name: Publish Python Package (fpl-extract-xml)

on:
  release:
    types: [published]

jobs:
  Release-PyPI-Package:
    runs-on: ubuntu-latest
    permissions:
      # this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Setup Python"
        uses: actions/setup-python@v4
      - name: "Install build"
        run: pip3 install build
      - name: Build
        run: python3 -m build tools/fpl-extract-xml
      - name: Publish distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: tools/fpl-extract-xml/dist
      - name: Publish distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: tools/fpl-extract-xml/dist
