#!/bin/sh

. ../../../scripts/test-utils.sh

fpl_write_pic=../../../bin/fpl-write-pic

compare()
{
  outfile=$1
  diff -u $outfile.ref.t $outfile.out.t > $outfile.diff.txt 2>&1
}

run_test()
{
  infile=$1
  if test -n "$2"
  then
    outfile=$2
  else
    outfile=$infile
  fi
  $fpl_write_pic < $infile.txt > $outfile.out.t 2>&1
  compare $outfile
}

. ./tests.sh

# Default tests
for t in $tests
do
  echo "
$t()
{
  run_test $t
}"
done > default-tests.sh
. ./default-tests.sh

run_suite $tests
